In [6]:
import numpy as np
import numpy.matlib
import math
import matplotlib.pyplot as plt
from math import floor, ceil
import random

def X(d,p1,mi): #update function
    for i2 in range (3):
        m6=np.mat(p1[:,i2]).T
        m2=np.hstack((m6,m6,m6,m6,m6))
        m3=np.multiply(d,m2)
        m4=np.sum(m3,axis=0)
        m5=np.sum(p1[:,i2],axis=0)
        m[i2,:]=m4/m5
        inter1=np.zeros((5,5))
        for j2 in range(len(d)):
            inter1=inter1+p1[j2,i2]*(d[j2,:]-mi[i2,:]).T@(d[j2,:]-mi[i2,:])
        s[:,:,i2]=inter1/np.sum(p1[:,i2],axis=0)
        p[0,i2]=np.sum(p1[:,i2],axis=0)/len(d)
    return p,s,m

d=np.loadtxt('GMDataSet_HW7.txt')
m=np.zeros((3,len(d[0]))) #means
s=np.zeros((len(d[0]),len(d[0]),3))#covariance
p=np.zeros((1,3)) #proportion
for i in range(3):
    ran=random.randint(1, len(d))
    m[i,:]=d[ran,:]
    s[:,:,i]=np.eye((len(d[0])))
    p[0,i]=0.25
it=1
th=10**(-6) #threshold
di=10 #difference
p1=np.zeros((len(d),3))

while  di>=th:
    for i in range(len(d)):
        for j in range (3):
            inter=p[0,j]*(1/(((2*math.pi)**len(d[0])*np.linalg.det(s[:,:,j]))**0.5))
            p1[i,j]=inter*np.exp(-0.5*(d[i,:]-m[j,:])@(np.linalg.inv(s[:,:,j]))@(d[i,:]-m[j,:]).T)
            
    m1=np.mat(np.sum(p1,axis=1)).T
    mm=np.hstack((m1,m1,m1))
    for i1 in range(len(p1)):
        for j1 in range(len(p1[0])):
            p1[i1,j1]=p1[i1,j1]/mm[i1,j1]
    mi=m #store last itineration values
    si=s
    pi=p
    p,s,m=X(d,p1,mi) #update values
    di1=np.sum(pi-p,axis=1)
    print(s)
    kkkk=np.sum(abs(mi-m),axis=0)
    print(kkkk)
    di2=np.sum(kkkk)
    di3=np.sum(np.sum(np.sum(abs(si-s),axis=0),axis=1),axis=2)
    di=di1+di2+di3
    it=it+1
print(m)
print(p)
print(si)


[[[ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]]

 [[ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]]

 [[ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]]

 [[ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]]

 [[ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13306641]
  [ 3.09515898  4.3953626   3.13

ValueError: 'axis' entry is out of bounds